import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
const dist = join(import.meta.dir, '../packages/web/dist'); const out: Record<string, string> = {};
const walk = (d: string) => { for (const f of readdirSync(d)) { const p = join(d, f); statSync(p).isDirectory() ? walk(p) : (out['/' + relative(dist, p).replace(/\\/g, '/')] = readFileSync(p).toString('base64')); } };
walk(dist);
writeFileSync(join(import.meta.dir, '../packages/cli/src/web-assets.ts'), `// generated by scripts/embed-web.ts — do not edit\nexport const WEB_ASSETS: Record<string, string> = ${JSON.stringify(out)};\n`);
console.log(`embedded ${Object.keys(out).length} files`);
